### ISSUE TITLE
Issue with sink file

### ISSUE THREAD

**Issue by ttepperg** [nvaytet/osyris#45]
Hi,

When I try to read a snapshot that contains sink particles I get the
following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tepper/Library/Python/3.7/lib/python/site-packages/osyris/core/dataset.py", line 63, in load
    groups = self.loader.load(*args, meta=self.meta, **kwargs)
  File "/Users/tepper/Library/Python/3.7/lib/python/site-packages/osyris/io/loader.py", line 81, in load
    select=select[group])
  File "/Users/tepper/Library/Python/3.7/lib/python/site-packages/osyris/io/sink.py", line 51, in initialize
    unit_list.append(eval(u.replace(' ', '*')))
  File "<string>", line 1
    1*
     ^
SyntaxError: unexpected EOF while parsing

**Comment by matthiasglz** [comment]
Hi,
I've just made a pull request that should fix your issue.

**Comment by ttepperg** [comment]
Hi Matthias,

Issue resolved, awesome!

Thanks a million.

Thor
